name: Build and publish a Docker image

on:
  pull_request:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mollux/docker-mautic

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mautic_version: [4.4.6, 5.x-dev]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: new_version/Dockerfile
          context: .
          build-args: |
            MAUTIC_VERSION=${{ matrix.mautic_version }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.mautic_version }}
          labels: ${{ steps.meta.outputs.labels }}
